### ISSUE TITLE
Breaks with AJAX

### ISSUE THREAD

**Issue by Kr3m** [WPGlobus/wpglobus-translate-options#1]
Per https://carrodel.com/inventory this plugin seems to not only break on the price field above each listing, but if you click on the AJAX pagination or any of the search dropdowns, it is completely destroyed.

**Comment by alexgff** [comment]
@Kr3m 
Please make sure this issue for WPGlobus Translate Options. Deactivate it and check again, may be the issue for WPGlobus

**Comment by tivnet** [comment]
(moved to www.wpglobus.com support ticket)
