### ISSUE TITLE
Use special option attribute instead of config files

### ISSUE THREAD

**Issue by dikiyforester** [WPGlobus/wpglobus-translate-options#2]
Config files is a bottleneck of this plugin since it requires continuously update them all.

In my experience, there are situations when some scripts don't even know which options and how many of them will be added, so it's impossible to write any config files or something similar.

As another solution, you could introduce a special attribute to option html which will just tell to your plugin "hey, i want you make my content translatable". This attribute might be added to any option/control. So theme/plugin developers can provide compatibility with your plugin once and forever.

PS: As themes/plugin developer, i'd avoid to write such config files for any of product that i maintain, i'd prefer to use something non static :smirk:

**Comment by alexgff** [comment]
done
